### ISSUE TITLE
Outstanding critical issues

### ISSUE THREAD

**Issue by austinyw** [BetterCloud/bigtable-orm#16]
This library has multiple outdated dependencies, some of which have critical issues. I have a PR to suggest fixes, however, it does so by force overwriting some dependencies. Tests pass but this will need extensive testing before releasing.

**Comment by austinyw** [comment]
https://github.com/BetterCloud/bigtable-orm/pull/17

**Comment by maxbettercloud** [comment]
Should be resolved by #19
